use_frameworks!

target 'FeatureFlags_Example' do
  #pod 'FeatureFlags', :path => '../'
  pod 'FeatureFlags', :git => 'https://github.com/vantientu1703/FeatureFlags.git'
  target 'FeatureFlags_Tests' do
    inherit! :search_paths

    
  end
end
